//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oldi.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oldi.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Port.
        /// </summary>
        public static string argumentPort {
            get {
                return ResourceManager.GetString("argumentPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SslPort.
        /// </summary>
        public static string argumentSslPort {
            get {
                return ResourceManager.GetString("argumentSslPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа службы прервана оператором.
        /// </summary>
        public static string cancelledByUser {
            get {
                return ResourceManager.GetString("cancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предъявлен клиентский сертификат.
        /// </summary>
        public static string clientCertificateReceived {
            get {
                return ResourceManager.GetString("clientCertificateReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка инициализации слушателя: Указан неверный номер порта.
        /// </summary>
        public static string invalidPortNumber {
            get {
                return ResourceManager.GetString("invalidPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка создания слушателя.
        /// </summary>
        public static string listenerCreationError {
            get {
                return ResourceManager.GetString("listenerCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слушатель запущен.
        /// </summary>
        public static string listenerStarted {
            get {
                return ResourceManager.GetString("listenerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка инициализации слушателя: Невозможно разрешить имя компьютера.
        /// </summary>
        public static string machineNameResolveError {
            get {
                return ResourceManager.GetString("machineNameResolveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Секция Кибер не найден в OLDIGW.xml.
        /// </summary>
        public static string MsgCyberSecNotFound {
            get {
                return ResourceManager.GetString("MsgCyberSecNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лицевой счет или телефон {0} не найден. Ошибка={1} {2}.
        /// </summary>
        public static string MsgFindFail {
            get {
                return ResourceManager.GetString("MsgFindFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о {0}.
        /// </summary>
        public static string MsgFindOK {
            get {
                return ResourceManager.GetString("MsgFindOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задание уже выполняется.
        /// </summary>
        public static string MsgJobAlreadyRunning {
            get {
                return ResourceManager.GetString("MsgJobAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задание не выполняется/остановлено.
        /// </summary>
        public static string MsgJobNotRunnig {
            get {
                return ResourceManager.GetString("MsgJobNotRunnig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка создания запрпоса.
        /// </summary>
        public static string MsgMRE {
            get {
                return ResourceManager.GetString("MsgMRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ шлюза:
        ///{0}.
        /// </summary>
        public static string MsgResponseGW {
            get {
                return ResourceManager.GetString("MsgResponseGW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер приложений не доступен.
        /// </summary>
        public static string MsgSNA {
            get {
                return ResourceManager.GetString("MsgSNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос успешно обработан.
        /// </summary>
        public static string MsgSUCS {
            get {
                return ResourceManager.GetString("MsgSUCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нераспознаваемый параметр &quot;{0}&quot;.
        /// </summary>
        public static string MsgUP {
            get {
                return ResourceManager.GetString("MsgUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестный провайдер &quot;{0}&quot;.
        /// </summary>
        public static string MsgURP {
            get {
                return ResourceManager.GetString("MsgURP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестный тип запроса. Ожидался &quot;{0}&quot;.
        /// </summary>
        public static string MsgURT {
            get {
                return ResourceManager.GetString("MsgURT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Usage: oldigw {command} [{key1} [{key2}]], где
        ///	command:
        ///		--noredo - запуск без допроведения (отладка)
        ///		--pays - передать реестр платежей MTS
        ///	Ключи:
        ///		--from dd.mm.yyyy - начальная дата реестра платежей MTS
        ///		--to dd.mm.yyyy - конечная дата реестра платежей MTS.
        /// </summary>
        public static string MsgUsage {
            get {
                return ResourceManager.GetString("MsgUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается сумму платежа: {0}.
        /// </summary>
        public static string MsgWaitPrice {
            get {
                return ResourceManager.GetString("MsgWaitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустмое значение параметра &quot;{0}={1}&quot;.
        /// </summary>
        public static string MsgWPV {
            get {
                return ResourceManager.GetString("MsgWPV", resourceCulture);
            }
        }
    }
}
