//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18063
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос выполнен успешно.
        /// </summary>
        internal static string ERR_0 {
            get {
                return ResourceManager.GetString("ERR_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер временно недоступен..
        /// </summary>
        internal static string ERR_1 {
            get {
                return ResourceManager.GetString("ERR_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платеж с таким идентификатором отсутствует.
        /// </summary>
        internal static string ERR_101 {
            get {
                return ResourceManager.GetString("ERR_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма платежа находится вне допустимого диапазона..
        /// </summary>
        internal static string ERR_102 {
            get {
                return ResourceManager.GetString("ERR_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Абонент не найден..
        /// </summary>
        internal static string ERR_12 {
            get {
                return ResourceManager.GetString("ERR_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос отклонен. .
        /// </summary>
        internal static string ERR_15 {
            get {
                return ResourceManager.GetString("ERR_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимое имя филиала..
        /// </summary>
        internal static string ERR_17 {
            get {
                return ResourceManager.GetString("ERR_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступ Агента к сервису ЕСПП запрещен..
        /// </summary>
        internal static string ERR_2 {
            get {
                return ResourceManager.GetString("ERR_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышена сумма допустимых операций по счету за период..
        /// </summary>
        internal static string ERR_21 {
            get {
                return ResourceManager.GetString("ERR_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный счёт/субсчёт, закрыт или заблокирован.
        /// </summary>
        internal static string ERR_22 {
            get {
                return ResourceManager.GetString("ERR_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена невозможна в связи с истечением срока давности. .
        /// </summary>
        internal static string ERR_23 {
            get {
                return ResourceManager.GetString("ERR_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестный / не поддерживаемый запрос.
        /// </summary>
        internal static string ERR_3 {
            get {
                return ResourceManager.GetString("ERR_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат запроса..
        /// </summary>
        internal static string ERR_4 {
            get {
                return ResourceManager.GetString("ERR_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимая валютаю..
        /// </summary>
        internal static string ERR_5 {
            get {
                return ResourceManager.GetString("ERR_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сертификат не содержит приватного ключа.
        /// </summary>
        internal static string MsgCHNPK {
            get {
                return ResourceManager.GetString("MsgCHNPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сертификат не найден.
        /// </summary>
        internal static string MsgCNF {
            get {
                return ResourceManager.GetString("MsgCNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платеж обрабатывается..
        /// </summary>
        internal static string STS_102 {
            get {
                return ResourceManager.GetString("STS_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платеж отменяется..
        /// </summary>
        internal static string STS_103 {
            get {
                return ResourceManager.GetString("STS_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платеж проведён..
        /// </summary>
        internal static string STS_2 {
            get {
                return ResourceManager.GetString("STS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платеж отменён..
        /// </summary>
        internal static string STS_3 {
            get {
                return ResourceManager.GetString("STS_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платеж отклонён..
        /// </summary>
        internal static string STS_4 {
            get {
                return ResourceManager.GetString("STS_4", resourceCulture);
            }
        }
    }
}
