//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18047
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oldi.Mts.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oldi.Mts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;Домашняя&quot; БС абонента на профилактике или недоступна. Для данного договора запрещено принимать платежи на основании данных ЦМ о номерной емкости.
        /// </summary>
        internal static string Error103 {
            get {
                return ResourceManager.GetString("Error103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЦМ не доступен.
        /// </summary>
        internal static string Error106 {
            get {
                return ResourceManager.GetString("Error106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прием платежа невозможен. Прием платежа запрещен (без детализации причины).
        /// </summary>
        internal static string Error200 {
            get {
                return ResourceManager.GetString("Error200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платеж не найден.
        /// </summary>
        internal static string Error2001 {
            get {
                return ResourceManager.GetString("Error2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платеж не удовлетворяет условиям отмены/возврата.
        /// </summary>
        internal static string Error2002 {
            get {
                return ResourceManager.GetString("Error2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Техническая ошибка.
        /// </summary>
        internal static string Error2003 {
            get {
                return ResourceManager.GetString("Error2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На данную запись уже был сформирован запрос.
        /// </summary>
        internal static string Error2004 {
            get {
                return ResourceManager.GetString("Error2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отказ без детализации.
        /// </summary>
        internal static string Error2005 {
            get {
                return ResourceManager.GetString("Error2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер телефона в БС не найден. Прием платежа запрещен (невозможен).
        /// </summary>
        internal static string Error201 {
            get {
                return ResourceManager.GetString("Error201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Представитель может получить отказ с кодом ошибки 20140 «Телефон не принадлежит тестовой номерной емкости» в том случае, если он при прохождении тестов в ходе сертификации ВПС [9] отправит платеж на телефон, номер которого не соответствует указанному в сценарии теста.
        /// </summary>
        internal static string Error20140 {
            get {
                return ResourceManager.GetString("Error20140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложение обслуживания не найдено. Прием платежа запрещен (невозможен).
        /// </summary>
        internal static string Error202 {
            get {
                return ResourceManager.GetString("Error202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Счет неактивен. Прием платежа запрещен (невозможен).
        /// </summary>
        internal static string Error203 {
            get {
                return ResourceManager.GetString("Error203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VIP счет. Прием платежа запрещен (невозможен).
        /// </summary>
        internal static string Error204 {
            get {
                return ResourceManager.GetString("Error204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание клиента не найдено. Прием платежа запрещен (невозможен).
        /// </summary>
        internal static string Error205 {
            get {
                return ResourceManager.GetString("Error205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрашиваемый номер л/с не найден.
        /// </summary>
        internal static string Error206 {
            get {
                return ResourceManager.GetString("Error206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Абонент является юридическим лицом. Прием платежей через СПП недопустим.
        /// </summary>
        internal static string Error207 {
            get {
                return ResourceManager.GetString("Error207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры платежа не соответствуют запросу разрешения на его прием.
        /// </summary>
        internal static string Error210 {
            get {
                return ResourceManager.GetString("Error210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прочие ошибки. Прием платежа запрещен (невозможен).
        /// </summary>
        internal static string Error299 {
            get {
                return ResourceManager.GetString("Error299", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прием платежа запрещен по административным причинам (без детализации причин).
        /// </summary>
        internal static string Error300 {
            get {
                return ResourceManager.GetString("Error300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий лимит недостаточен для приема платежа. Прием платежа запрещен.
        /// </summary>
        internal static string Error301 {
            get {
                return ResourceManager.GetString("Error301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не определен ПЦ Представителя (код отправителя) платежа.
        /// </summary>
        internal static string Error350 {
            get {
                return ResourceManager.GetString("Error350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найден договор между Представителем  и Участником.
        /// </summary>
        internal static string Error351 {
            get {
                return ResourceManager.GetString("Error351", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Договор между Представителем и Участником не активен.
        /// </summary>
        internal static string Error352 {
            get {
                return ResourceManager.GetString("Error352", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервис отключен.
        /// </summary>
        internal static string Error353 {
            get {
                return ResourceManager.GetString("Error353", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Терминал не зарегистрирован.
        /// </summary>
        internal static string Error354 {
            get {
                return ResourceManager.GetString("Error354", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платеж уже существует.
        /// </summary>
        internal static string Error357 {
            get {
                return ResourceManager.GetString("Error357", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет запроса на прием платежа.
        /// </summary>
        internal static string Error358 {
            get {
                return ResourceManager.GetString("Error358", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет разрешения приема платежа.
        /// </summary>
        internal static string Error359 {
            get {
                return ResourceManager.GetString("Error359", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещенный интерфейс приема платежей.
        /// </summary>
        internal static string Error360 {
            get {
                return ResourceManager.GetString("Error360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период сверки закрыт.
        /// </summary>
        internal static string Error361 {
            get {
                return ResourceManager.GetString("Error361", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата операции будущая.
        /// </summary>
        internal static string Error362 {
            get {
                return ResourceManager.GetString("Error362", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрещен прием платежей с будущей датой операции вне допустимого диапазона.
        /// </summary>
        internal static string Error363 {
            get {
                return ResourceManager.GetString("Error363", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прием платежей на терминал запрещен.
        /// </summary>
        internal static string Error366 {
            get {
                return ResourceManager.GetString("Error366", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Истекло время акцептования документа.
        /// </summary>
        internal static string Error398 {
            get {
                return ResourceManager.GetString("Error398", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БС. Для данной комбинации условий [банк, платежный инструмент, код типа терминала] прием платежа административно запрещен.
        /// </summary>
        internal static string Error399 {
            get {
                return ResourceManager.GetString("Error399", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не определены необходимые данные.
        /// </summary>
        internal static string Error400 {
            get {
                return ResourceManager.GetString("Error400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышена пропускная способность.
        /// </summary>
        internal static string Error501 {
            get {
                return ResourceManager.GetString("Error501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Истекло время обработки.
        /// </summary>
        internal static string Error502 {
            get {
                return ResourceManager.GetString("Error502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БС. Техническая ошибка Oracle.
        /// </summary>
        internal static string Error64 {
            get {
                return ResourceManager.GetString("Error64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПЦ ЕСПП. Техническая ошибка Oracle.
        /// </summary>
        internal static string Error65 {
            get {
                return ResourceManager.GetString("Error65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не определено состояние платежа .
        /// </summary>
        internal static string Error650 {
            get {
                return ResourceManager.GetString("Error650", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платеж в требуемом состоянии не найден.
        /// </summary>
        internal static string Error651 {
            get {
                return ResourceManager.GetString("Error651", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПЦ ЕСПП. Техническая ошибка сервера приложений.
        /// </summary>
        internal static string Error66 {
            get {
                return ResourceManager.GetString("Error66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер телефона содержит нечисловые символы.
        /// </summary>
        internal static string Error71 {
            get {
                return ResourceManager.GetString("Error71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестный формат реестра.
        /// </summary>
        internal static string Error801 {
            get {
                return ResourceManager.GetString("Error801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестный алгоритм архивации реестра.
        /// </summary>
        internal static string Error802 {
            get {
                return ResourceManager.GetString("Error802", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Входной контроль файла сверки. Расшифровка в описании ошибки.
        /// </summary>
        internal static string Error803 {
            get {
                return ResourceManager.GetString("Error803", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идентификатор реестра для проведения сверки не найден.
        /// </summary>
        internal static string Error804 {
            get {
                return ResourceManager.GetString("Error804", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По данному реестру сверка не завершена.
        /// </summary>
        internal static string Error805 {
            get {
                return ResourceManager.GetString("Error805", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Техническая ошибка.
        /// </summary>
        internal static string Error806 {
            get {
                return ResourceManager.GetString("Error806", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на За данный период выполняется сверка до другому реестру. Сверка не завершена.
        /// </summary>
        internal static string Error807 {
            get {
                return ResourceManager.GetString("Error807", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно принять решение о приеме платежей в пакетном режиме.
        /// </summary>
        internal static string Error999 {
            get {
                return ResourceManager.GetString("Error999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно загрузить шаблон.
        /// </summary>
        internal static string MsgCLT {
            get {
                return ResourceManager.GetString("MsgCLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MTS: Запущен процесс обработки реестров..
        /// </summary>
        internal static string MsgRedoRunning {
            get {
                return ResourceManager.GetString("MsgRedoRunning", resourceCulture);
            }
        }
    }
}
