//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18034
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oldi.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oldi.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указанная запись не была найдена в кэше..
        /// </summary>
        internal static string CacheEntryNotFound {
            get {
                return ResourceManager.GetString("CacheEntryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на С точкой удаленной службы нельзя связаться на транспортном уровне..
        /// </summary>
        internal static string ConnectFailure {
            get {
                return ResourceManager.GetString("ConnectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключение было преждевременно закрыто..
        /// </summary>
        internal static string ConnectionClosed {
            get {
                return ResourceManager.GetString("ConnectionClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос успешно выполнен.
        /// </summary>
        internal static string Error0 {
            get {
                return ResourceManager.GetString("Error0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидание завершения операции.
        /// </summary>
        internal static string Error03 {
            get {
                return ResourceManager.GetString("Error03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сессия с таким номером уже существует.
        /// </summary>
        internal static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат запроса.
        /// </summary>
        internal static string Error10 {
            get {
                return ResourceManager.GetString("Error10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат ответа, либо ответ не получен.
        /// </summary>
        internal static string Error100 {
            get {
                return ResourceManager.GetString("Error100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сессия с таким номером не существует.
        /// </summary>
        internal static string Error11 {
            get {
                return ResourceManager.GetString("Error11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос сделан с незарегистрированного IP.
        /// </summary>
        internal static string Error12 {
            get {
                return ResourceManager.GetString("Error12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Точка не зарегистрирована у Получателя.
        /// </summary>
        internal static string Error13 {
            get {
                return ResourceManager.GetString("Error13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платежи данному Получателю не поддерживаются системой.
        /// </summary>
        internal static string Error15 {
            get {
                return ResourceManager.GetString("Error15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер телефона не соответствует введенному ранее.
        /// </summary>
        internal static string Error17 {
            get {
                return ResourceManager.GetString("Error17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма к зачислению не соответствует введенной ранее.
        /// </summary>
        internal static string Error18 {
            get {
                return ResourceManager.GetString("Error18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер счета (контракта) не соответствует введенному ранее.
        /// </summary>
        internal static string Error19 {
            get {
                return ResourceManager.GetString("Error19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный код контрагента.
        /// </summary>
        internal static string Error2 {
            get {
                return ResourceManager.GetString("Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платеж находится в состоянии завершения.
        /// </summary>
        internal static string Error20 {
            get {
                return ResourceManager.GetString("Error20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно средств для проведения платежа.
        /// </summary>
        internal static string Error21 {
            get {
                return ResourceManager.GetString("Error21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платеж не принят. Ошибка при переводе средств.
        /// </summary>
        internal static string Error22 {
            get {
                return ResourceManager.GetString("Error22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контракт клиента не позволяет производить пополнение счета.
        /// </summary>
        internal static string Error223 {
            get {
                return ResourceManager.GetString("Error223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный номер телефона/счета.
        /// </summary>
        internal static string Error23 {
            get {
                return ResourceManager.GetString("Error23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка связи с сервером Получателя.
        /// </summary>
        internal static string Error24 {
            get {
                return ResourceManager.GetString("Error24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Работа шлюза приостановлена.
        /// </summary>
        internal static string Error25 {
            get {
                return ResourceManager.GetString("Error25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платежи данного Контрагента временно блокированы.
        /// </summary>
        internal static string Error26 {
            get {
                return ResourceManager.GetString("Error26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операции по счету приостановлены.
        /// </summary>
        internal static string Error27 {
            get {
                return ResourceManager.GetString("Error27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный код точки приема.
        /// </summary>
        internal static string Error3 {
            get {
                return ResourceManager.GetString("Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общая ошибка системы.
        /// </summary>
        internal static string Error30 {
            get {
                return ResourceManager.GetString("Error30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышено количество одновременно обрабатываемых запросов (Киберплат).
        /// </summary>
        internal static string Error31 {
            get {
                return ResourceManager.GetString("Error31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платеж с этими данными уже был принят к обработке за последний час.
        /// </summary>
        internal static string Error32 {
            get {
                return ResourceManager.GetString("Error32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карты указанного номинала на данный момент в системе отсутствуют.
        /// </summary>
        internal static string Error33 {
            get {
                return ResourceManager.GetString("Error33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Транзакция с таким номером не найдена.
        /// </summary>
        internal static string Error34 {
            get {
                return ResourceManager.GetString("Error34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при изменении состояния платежа.
        /// </summary>
        internal static string Error35 {
            get {
                return ResourceManager.GetString("Error35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Транзакция уже завершена или находится в обработке.
        /// </summary>
        internal static string Error36 {
            get {
                return ResourceManager.GetString("Error36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка обращения в шлюз, отличный от шлюза на предыдущем шаге.
        /// </summary>
        internal static string Error37 {
            get {
                return ResourceManager.GetString("Error37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышен лимит времени между проверкой номера и платежом (1 час).
        /// </summary>
        internal static string Error38 {
            get {
                return ResourceManager.GetString("Error38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный счет учета.
        /// </summary>
        internal static string Error39 {
            get {
                return ResourceManager.GetString("Error39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный код оператора точки приема.
        /// </summary>
        internal static string Error4 {
            get {
                return ResourceManager.GetString("Error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карта указанного номинала в системе не зарегистрирована.
        /// </summary>
        internal static string Error40 {
            get {
                return ResourceManager.GetString("Error40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка добавления данных платежа в базу данных.
        /// </summary>
        internal static string Error41 {
            get {
                return ResourceManager.GetString("Error41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при сохранении чека в базе данных.
        /// </summary>
        internal static string Error42 {
            get {
                return ResourceManager.GetString("Error42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сеанс Вашей работы в системе недействителен (возможно, истек срок действия сессии), попробуйте войти заново.
        /// </summary>
        internal static string Error43 {
            get {
                return ResourceManager.GetString("Error43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клиент не может работать на этом торговом сервере.
        /// </summary>
        internal static string Error44 {
            get {
                return ResourceManager.GetString("Error44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует разрешение на прием платежей в пользу данного Получателя.
        /// </summary>
        internal static string Error45 {
            get {
                return ResourceManager.GetString("Error45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось завершить ошибочный платеж.
        /// </summary>
        internal static string Error46 {
            get {
                return ResourceManager.GetString("Error46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сработало временнОе ограничение прав.
        /// </summary>
        internal static string Error47 {
            get {
                return ResourceManager.GetString("Error47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при сохранении в системе данных сессии.
        /// </summary>
        internal static string Error48 {
            get {
                return ResourceManager.GetString("Error48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при сохранении в системе данных отказа при платеже.
        /// </summary>
        internal static string Error49 {
            get {
                return ResourceManager.GetString("Error49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат кода сессии.
        /// </summary>
        internal static string Error5 {
            get {
                return ResourceManager.GetString("Error5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проведение платежей в системе временно невозможно.
        /// </summary>
        internal static string Error50 {
            get {
                return ResourceManager.GetString("Error50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдены данные в системе.
        /// </summary>
        internal static string Error51 {
            get {
                return ResourceManager.GetString("Error51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возможно, контрагент заблокирован..
        /// </summary>
        internal static string Error52 {
            get {
                return ResourceManager.GetString("Error52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возможно, точка приема заблокирована..
        /// </summary>
        internal static string Error53 {
            get {
                return ResourceManager.GetString("Error53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возможно, оператор точки приема заблокирован..
        /// </summary>
        internal static string Error54 {
            get {
                return ResourceManager.GetString("Error54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидался контрагент другого типа.
        /// </summary>
        internal static string Error55 {
            get {
                return ResourceManager.GetString("Error55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидалась точка другого типа.
        /// </summary>
        internal static string Error56 {
            get {
                return ResourceManager.GetString("Error56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидался оператор точки приема другого типа..
        /// </summary>
        internal static string Error57 {
            get {
                return ResourceManager.GetString("Error57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверная АСП.
        /// </summary>
        internal static string Error6 {
            get {
                return ResourceManager.GetString("Error6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат или значение суммы к зачислению вне допустимого диапазона.
        /// </summary>
        internal static string Error7 {
            get {
                return ResourceManager.GetString("Error7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указана дата завершения действия карты для данного номинала.
        /// </summary>
        internal static string Error71 {
            get {
                return ResourceManager.GetString("Error71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер карты и ПИН-код должны быть уникальными в рамках одного получателя.
        /// </summary>
        internal static string Error72 {
            get {
                return ResourceManager.GetString("Error72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат номера телефона.
        /// </summary>
        internal static string Error8 {
            get {
                return ResourceManager.GetString("Error8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышена максимальная сумма платежа по Контрагенту.
        /// </summary>
        internal static string Error81 {
            get {
                return ResourceManager.GetString("Error81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышена сумма списаний за день по Контрагенту.
        /// </summary>
        internal static string Error82 {
            get {
                return ResourceManager.GetString("Error82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышена максимальная сумма платежа по точке.
        /// </summary>
        internal static string Error83 {
            get {
                return ResourceManager.GetString("Error83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышена сумма списаний за день по точке.
        /// </summary>
        internal static string Error84 {
            get {
                return ResourceManager.GetString("Error84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат или значение полной суммы вне допустимого диапазона.
        /// </summary>
        internal static string Error85 {
            get {
                return ResourceManager.GetString("Error85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка системы (неверное значение ставки).
        /// </summary>
        internal static string Error86 {
            get {
                return ResourceManager.GetString("Error86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат номера лицевого счета.
        /// </summary>
        internal static string Error9 {
            get {
                return ResourceManager.GetString("Error9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неожиданно закрыто подключение для запроса, задающего заголовок Keep-alive..
        /// </summary>
        internal static string KeepAliveFailure {
            get {
                return ResourceManager.GetString("KeepAliveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принято сообщение о превышении заданного ограничения при передаче запроса или приеме ответа сервера..
        /// </summary>
        internal static string MessageLengthLimitExceeded {
            get {
                return ResourceManager.GetString("MessageLengthLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ провайдера: {0} ({1})
        ///=======
        ///{2}
        ///=======.
        /// </summary>
        internal static string MsgAnswer {
            get {
                return ResourceManager.GetString("MsgAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка получения ответа от провайдера.
        /// </summary>
        internal static string MsgAnswerError {
            get {
                return ResourceManager.GetString("MsgAnswerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сертификат не содержит закрытого ключа.
        /// </summary>
        internal static string MsgCHNPK {
            get {
                return ResourceManager.GetString("MsgCHNPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно загрузить шаблон.
        /// </summary>
        internal static string MsgCLT {
            get {
                return ResourceManager.GetString("MsgCLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сертификат не найден.
        /// </summary>
        internal static string MsgCNF {
            get {
                return ResourceManager.GetString("MsgCNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не получен или получен пустой ответ от провайдера.
        /// </summary>
        internal static string MsgEmptyAnswer {
            get {
                return ResourceManager.GetString("MsgEmptyAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пустой запрос.
        /// </summary>
        internal static string MsgER {
            get {
                return ResourceManager.GetString("MsgER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [FIND]: Id={0} ErrCode={1} ErrDesc={2}.
        /// </summary>
        internal static string MsgFindFail {
            get {
                return ResourceManager.GetString("MsgFindFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [FIND]: Id={0} {1}.
        /// </summary>
        internal static string MsgFindOK {
            get {
                return ResourceManager.GetString("MsgFindOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функция {0} не реализована.
        /// </summary>
        internal static string MsgFNI {
            get {
                return ResourceManager.GetString("MsgFNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка создания запрпоса.
        /// </summary>
        internal static string MsgMRE {
            get {
                return ResourceManager.GetString("MsgMRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ от провайдера не получен.
        /// </summary>
        internal static string MsgNoAnswer {
            get {
                return ResourceManager.GetString("MsgNoAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обработка [{0}] не реализована.
        /// </summary>
        internal static string MsgNR {
            get {
                return ResourceManager.GetString("MsgNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка разбора ответа.
        /// </summary>
        internal static string MsgParseAnswer {
            get {
                return ResourceManager.GetString("MsgParseAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка разбора {0} {1}.
        /// </summary>
        internal static string MsgParsingError {
            get {
                return ResourceManager.GetString("MsgParsingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер приложений не доступен.
        /// </summary>
        internal static string MsgSNA {
            get {
                return ResourceManager.GetString("MsgSNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос успешно обработан.
        /// </summary>
        internal static string MsgSUCS {
            get {
                return ResourceManager.GetString("MsgSUCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка шаблона платежа.
        /// </summary>
        internal static string MsgTemplateError {
            get {
                return ResourceManager.GetString("MsgTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нераспознанный параметр.
        /// </summary>
        internal static string MsgUP {
            get {
                return ResourceManager.GetString("MsgUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестный провайдер &quot;{0}&quot;.
        /// </summary>
        internal static string MsgURP {
            get {
                return ResourceManager.GetString("MsgURP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестный тип запроса &quot;{0}&quot;.
        /// </summary>
        internal static string MsgURT {
            get {
                return ResourceManager.GetString("MsgURT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка проверки ЭЦП провайдера.
        /// </summary>
        internal static string MsgVerify {
            get {
                return ResourceManager.GetString("MsgVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ожидается сумма.
        /// </summary>
        internal static string MsgWaitPrice {
            get {
                return ResourceManager.GetString("MsgWaitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверное значение параметра.
        /// </summary>
        internal static string MsgWPV {
            get {
                return ResourceManager.GetString("MsgWPV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Служба разрешения имен не может разрешить имя узла..
        /// </summary>
        internal static string NameResolutionFailure {
            get {
                return ResourceManager.GetString("NameResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутренний асинхронный запрос находится в очереди..
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос являлся конвейерным запросом, и подключение было закрыто до получения запроса..
        /// </summary>
        internal static string PipelineFailure {
            get {
                return ResourceManager.GetString("PipelineFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ, принятый от сервера, был завершен, но указал на ошибку на уровне протокола..
        /// </summary>
        internal static string ProtocolError {
            get {
                return ResourceManager.GetString("ProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Служба разрешения имен не может распознать имя узла прокси-сервера..
        /// </summary>
        internal static string ProxyNameResolutionFailure {
            get {
                return ResourceManager.GetString("ProxyNameResolutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От удаленного сервера не был получен полный ответ..
        /// </summary>
        internal static string ReceiveFailure {
            get {
                return ResourceManager.GetString("ReceiveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрос был отменен, был вызван метод WebRequest.Abort или возникла ошибка, не поддающаяся классификации..
        /// </summary>
        internal static string RequestCanceled {
            get {
                return ResourceManager.GetString("RequestCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот запрос не разрешен политикой кэширования.
        /// </summary>
        internal static string RequestProhibitedByCachePolicy {
            get {
                return ResourceManager.GetString("RequestProhibitedByCachePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот запрос не разрешен прокси-сервером..
        /// </summary>
        internal static string RequestProhibitedByProxy {
            get {
                return ResourceManager.GetString("RequestProhibitedByProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При установлении подключения с использованием SSL произошла ошибка..
        /// </summary>
        internal static string SecureChannelFailure {
            get {
                return ResourceManager.GetString("SecureChannelFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полный запрос не был передан на удаленный сервер..
        /// </summary>
        internal static string SendFailure {
            get {
                return ResourceManager.GetString("SendFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ сервера не являлся допустимым ответом HTTP..
        /// </summary>
        internal static string ServerProtocolViolation {
            get {
                return ResourceManager.GetString("ServerProtocolViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибок не было..
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В течение времени ожидания запроса ответ получен не был..
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сертификат сервера не может быть проверен..
        /// </summary>
        internal static string TrustFailure {
            get {
                return ResourceManager.GetString("TrustFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возникло исключение неизвестного типа..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
