//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oldi.Net.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int СodeSNA {
            get {
                return ((int)(this["СodeSNA"]));
            }
            set {
                this["СodeSNA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<response>\r\n\t<error code=\"{0}\">{1}</error> \r\n</response>")]
        public string FailResponse {
            get {
                return ((string)(this["FailResponse"]));
            }
            set {
                this["FailResponse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-8\"?>")]
        public string XmlHeader {
            get {
                return ((string)(this["XmlHeader"]));
            }
            set {
                this["XmlHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int CodeSUCS {
            get {
                return ((int)(this["CodeSUCS"]));
            }
            set {
                this["CodeSUCS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int CodeFail {
            get {
                return ((int)(this["CodeFail"]));
            }
            set {
                this["CodeFail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CodeWait {
            get {
                return ((int)(this["CodeWait"]));
            }
            set {
                this["CodeWait"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int CodeTryAgain {
            get {
                return ((int)(this["CodeTryAgain"]));
            }
            set {
                this["CodeTryAgain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int CodeLongWait {
            get {
                return ((int)(this["CodeLongWait"]));
            }
            set {
                this["CodeLongWait"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mts")]
        public string ProviderMTS {
            get {
                return ((string)(this["ProviderMTS"]));
            }
            set {
                this["ProviderMTS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cyber")]
        public string ProviderCyber {
            get {
                return ((string)(this["ProviderCyber"]));
            }
            set {
                this["ProviderCyber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pcc")]
        public string ProviderPCC {
            get {
                return ((string)(this["ProviderPCC"]));
            }
            set {
                this["ProviderPCC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("upc")]
        public string ProviderUPC {
            get {
                return ((string)(this["ProviderUPC"]));
            }
            set {
                this["ProviderUPC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ekt")]
        public string ProviderEKT {
            get {
                return ((string)(this["ProviderEKT"]));
            }
            set {
                this["ProviderEKT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rapida")]
        public string ProviderRapida {
            get {
                return ((string)(this["ProviderRapida"]));
            }
            set {
                this["ProviderRapida"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<response>\r\n\t<error code=\"{0}\">{1}</error> \r\n\t<transaction>{2}</transaction>\r\n\t<a" +
            "cceptdate>{3}</acceptdate>\r\n\t<acceptcode>{4}</acceptcode>\r\n\t<account>{5}</accoun" +
            "t>\r\n\t<addinfo>{6}</addinfo>\r\n</response>")]
        public string Response {
            get {
                return ((string)(this["Response"]));
            }
            set {
                this["Response"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Success {
            get {
                return ((int)(this["Success"]));
            }
            set {
                this["Success"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10001")]
        public int NameResolutionFailure {
            get {
                return ((int)(this["NameResolutionFailure"]));
            }
            set {
                this["NameResolutionFailure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10002")]
        public int ConnectFailure {
            get {
                return ((int)(this["ConnectFailure"]));
            }
            set {
                this["ConnectFailure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10003")]
        public int ReceiveFailure {
            get {
                return ((int)(this["ReceiveFailure"]));
            }
            set {
                this["ReceiveFailure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10004")]
        public int SendFailure {
            get {
                return ((int)(this["SendFailure"]));
            }
            set {
                this["SendFailure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10005")]
        public int PipelineFailure {
            get {
                return ((int)(this["PipelineFailure"]));
            }
            set {
                this["PipelineFailure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10006")]
        public int RequestCanceled {
            get {
                return ((int)(this["RequestCanceled"]));
            }
            set {
                this["RequestCanceled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10007")]
        public int ProtocolError {
            get {
                return ((int)(this["ProtocolError"]));
            }
            set {
                this["ProtocolError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10008")]
        public int ConnectionClosed {
            get {
                return ((int)(this["ConnectionClosed"]));
            }
            set {
                this["ConnectionClosed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10009")]
        public int TrustFailure {
            get {
                return ((int)(this["TrustFailure"]));
            }
            set {
                this["TrustFailure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10010")]
        public int SecureChannelFailure {
            get {
                return ((int)(this["SecureChannelFailure"]));
            }
            set {
                this["SecureChannelFailure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10011")]
        public int ServerProtocolViolation {
            get {
                return ((int)(this["ServerProtocolViolation"]));
            }
            set {
                this["ServerProtocolViolation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10012")]
        public int KeepAliveFailure {
            get {
                return ((int)(this["KeepAliveFailure"]));
            }
            set {
                this["KeepAliveFailure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10013")]
        public int Pending {
            get {
                return ((int)(this["Pending"]));
            }
            set {
                this["Pending"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10014")]
        public int Timeout {
            get {
                return ((int)(this["Timeout"]));
            }
            set {
                this["Timeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10015")]
        public int ProxyNameResolutionFailure {
            get {
                return ((int)(this["ProxyNameResolutionFailure"]));
            }
            set {
                this["ProxyNameResolutionFailure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10016")]
        public int UnknownError {
            get {
                return ((int)(this["UnknownError"]));
            }
            set {
                this["UnknownError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10017")]
        public int MessageLengthLimitExceeded {
            get {
                return ((int)(this["MessageLengthLimitExceeded"]));
            }
            set {
                this["MessageLengthLimitExceeded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10018")]
        public int CacheEntryNotFound {
            get {
                return ((int)(this["CacheEntryNotFound"]));
            }
            set {
                this["CacheEntryNotFound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10019")]
        public int RequestProhibitedByCachePolicy {
            get {
                return ((int)(this["RequestProhibitedByCachePolicy"]));
            }
            set {
                this["RequestProhibitedByCachePolicy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10020")]
        public int RequestProhibitedByProxy {
            get {
                return ((int)(this["RequestProhibitedByProxy"]));
            }
            set {
                this["RequestProhibitedByProxy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"windows-1251\"?>")]
        public string XmlHeader1251 {
            get {
                return ((string)(this["XmlHeader1251"]));
            }
            set {
                this["XmlHeader1251"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OLDIGW")]
        public string SessionPrefix {
            get {
                return ((string)(this["SessionPrefix"]));
            }
            set {
                this["SessionPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int CodeLongLongWait {
            get {
                return ((int)(this["CodeLongLongWait"]));
            }
            set {
                this["CodeLongLongWait"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEBUG")]
        public string LogLevel {
            get {
                return ((string)(this["LogLevel"]));
            }
            set {
                this["LogLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<response>\r\n\t<error code=\"{0}\">{1}</error> \r\n\t<balance>{2}</balance>\r\n</response>" +
            "")]
        public string BalanceResponse {
            get {
                return ((string)(this["BalanceResponse"]));
            }
            set {
                this["BalanceResponse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ожидается платеж на сумму {0}")]
        public string MsgWaitPrice {
            get {
                return ((string)(this["MsgWaitPrice"]));
            }
            set {
                this["MsgWaitPrice"] = value;
            }
        }
    }
}
