//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oldi.Mts.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version = ""1.0"" encoding = ""UTF-8""?>
<{0}\txmlns = ""http://schema.mts.ru/ESPP/AgentPayments/Protocol/Messages/v5_02""
				xmlns:espp-constraints = ""http://schema.mts.ru/ESPP/Core/Constraints/v5_02""
				xmlns:xsi = ""http://www.w3.org/2001/XMLSchema-instance""
				xsi:schemaLocation = ""http://schema.mts.ru/ESPP/AgentPayments/Protocol/Messages/v5_02 ESPP_AgentPayments_Protocol_Messages_v5_02.xsd
									  http://schema.mts.ru/ESPP/Core/Constraints/v5_02 ESPP_Core_Constraints_v5_02.xsd""
				{1}>
")]
        public string Header {
            get {
                return ((string)(this["Header"]));
            }
            set {
                this["Header"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("</{0}>")]
        public string Footer {
            get {
                return ((string)(this["Footer"]));
            }
            set {
                this["Footer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<{0} xsi:type = \"espp-constraints:{1}\">{2}</{0}>")]
        public string Tag1 {
            get {
                return ((string)(this["Tag1"]));
            }
            set {
                this["Tag1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<{0}>{1}</{0}>")]
        public string Tag2 {
            get {
                return ((string)(this["Tag2"]));
            }
            set {
                this["Tag2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://schema.mts.ru/ESPP/AgentPayments/Protocol/Messages/v{0}")]
        public string UrlMessages {
            get {
                return ((string)(this["UrlMessages"]));
            }
            set {
                this["UrlMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ESPP_AgentPayments_Protocol_Messages_v{0}.xsd")]
        public string XsdMessages {
            get {
                return ((string)(this["XsdMessages"]));
            }
            set {
                this["XsdMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://schema.mts.ru/ESPP/Core/Constraints/v{0}")]
        public string UrlConstraints {
            get {
                return ((string)(this["UrlConstraints"]));
            }
            set {
                this["UrlConstraints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ESPP_Core_Constraints_v{0}.xsd")]
        public string XsdConstraints {
            get {
                return ((string)(this["XsdConstraints"]));
            }
            set {
                this["XsdConstraints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ESPP_0104010")]
        public string CheckTemplate {
            get {
                return ((string)(this["CheckTemplate"]));
            }
            set {
                this["CheckTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ESPP_0104090")]
        public string PayTemplate {
            get {
                return ((string)(this["PayTemplate"]));
            }
            set {
                this["PayTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ESPP_0104085")]
        public string StatusTemplate {
            get {
                return ((string)(this["StatusTemplate"]));
            }
            set {
                this["StatusTemplate"] = value;
            }
        }
    }
}
