//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oldi.Ekt {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oldi.Ekt.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверно указан номер.
        /// </summary>
        internal static string Code1 {
            get {
                return ResourceManager.GetString("Code1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фатальная ошибка провайдера.
        /// </summary>
        internal static string Code10 {
            get {
                return ResourceManager.GetString("Code10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нехватка средств (без повторов).
        /// </summary>
        internal static string Code12 {
            get {
                return ResourceManager.GetString("Code12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутренняя: Таймаут обработки.
        /// </summary>
        internal static string Code13 {
            get {
                return ResourceManager.GetString("Code13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутренняя: Платеж отменен плательщиком.
        /// </summary>
        internal static string Code14 {
            get {
                return ResourceManager.GetString("Code14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутренняя: Нехватка средств на счете агента.
        /// </summary>
        internal static string Code15 {
            get {
                return ResourceManager.GetString("Code15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутренняя: Отменена тех.поддержкой.
        /// </summary>
        internal static string Code16 {
            get {
                return ResourceManager.GetString("Code16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат идентификатора абонента (КабINET).
        /// </summary>
        internal static string Code17 {
            get {
                return ResourceManager.GetString("Code17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет связи с сервером провайдера (24).
        /// </summary>
        internal static string Code18 {
            get {
                return ResourceManager.GetString("Code18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыт шлюз у оператора.
        /// </summary>
        internal static string Code19 {
            get {
                return ResourceManager.GetString("Code19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверно указан номер.
        /// </summary>
        internal static string Code2 {
            get {
                return ResourceManager.GetString("Code2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прием платежа блокирован на стороне провайдера.
        /// </summary>
        internal static string Code20 {
            get {
                return ResourceManager.GetString("Code20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка Базы Данных у провайдера.
        /// </summary>
        internal static string Code21 {
            get {
                return ResourceManager.GetString("Code21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный номер телефона/счета(Евротел).
        /// </summary>
        internal static string Code22 {
            get {
                return ResourceManager.GetString("Code22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма вне допустимого диапазона.
        /// </summary>
        internal static string Code3 {
            get {
                return ResourceManager.GetString("Code3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно средств на счете провайдера.
        /// </summary>
        internal static string Code30 {
            get {
                return ResourceManager.GetString("Code30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервис не подключен.
        /// </summary>
        internal static string Code33 {
            get {
                return ResourceManager.GetString("Code33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер провайдера недоступен.
        /// </summary>
        internal static string Code4 {
            get {
                return ResourceManager.GetString("Code4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка авторизации.
        /// </summary>
        internal static string Code5 {
            get {
                return ResourceManager.GetString("Code5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер оператора недоступен.
        /// </summary>
        internal static string Code6 {
            get {
                return ResourceManager.GetString("Code6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общая ошибка провайдера.
        /// </summary>
        internal static string Code7 {
            get {
                return ResourceManager.GetString("Code7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фатальная ошибка платежной системы.
        /// </summary>
        internal static string Code8 {
            get {
                return ResourceManager.GetString("Code8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверные параметры проведения.
        /// </summary>
        internal static string Code9 {
            get {
                return ResourceManager.GetString("Code9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не заполнено поле AMOUNT.
        /// </summary>
        internal static string Err_NoAmount {
            get {
                return ResourceManager.GetString("Err_NoAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ekt.MakeRequest: Не заданы обязательные параметры.
        /// </summary>
        internal static string Err_NoDefaults {
            get {
                return ResourceManager.GetString("Err_NoDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ekt.MakeRequest: Неизвестное состояние {0} при построении запроса.
        /// </summary>
        internal static string Err_UnknownState {
            get {
                return ResourceManager.GetString("Err_UnknownState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка вставки операции в БД.
        /// </summary>
        internal static string State_minus_1 {
            get {
                return ResourceManager.GetString("State_minus_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платеж не найден при проверке статуса.
        /// </summary>
        internal static string State_minus_2 {
            get {
                return ResourceManager.GetString("State_minus_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый.
        /// </summary>
        internal static string State0 {
            get {
                return ResourceManager.GetString("State0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Финансовый контроль.
        /// </summary>
        internal static string State10 {
            get {
                return ResourceManager.GetString("State10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готов к списанию.
        /// </summary>
        internal static string State20_1 {
            get {
                return ResourceManager.GetString("State20_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Списание средств со счета.
        /// </summary>
        internal static string State20_2_3 {
            get {
                return ResourceManager.GetString("State20_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно средств на счете.
        /// </summary>
        internal static string State20_4 {
            get {
                return ResourceManager.GetString("State20_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Списание:: (20/{0}/{1}).
        /// </summary>
        internal static string State20_X {
            get {
                return ResourceManager.GetString("State20_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готов к проведению.
        /// </summary>
        internal static string State40_1 {
            get {
                return ResourceManager.GetString("State40_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проведение.
        /// </summary>
        internal static string State40_2_3 {
            get {
                return ResourceManager.GetString("State40_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка проведения.
        /// </summary>
        internal static string State40_4_5 {
            get {
                return ResourceManager.GetString("State40_4_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проведение (40/{0}/{1}).
        /// </summary>
        internal static string State40_X {
            get {
                return ResourceManager.GetString("State40_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проведён.
        /// </summary>
        internal static string State60 {
            get {
                return ResourceManager.GetString("State60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платёж отменён вручную.
        /// </summary>
        internal static string State80_1_2_3 {
            get {
                return ResourceManager.GetString("State80_1_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменён: недостаточно средств на счете.
        /// </summary>
        internal static string State80_4 {
            get {
                return ResourceManager.GetString("State80_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменён: общая ошибка.
        /// </summary>
        internal static string State80_5 {
            get {
                return ResourceManager.GetString("State80_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменён: неизвестная ошибка.
        /// </summary>
        internal static string State80_6 {
            get {
                return ResourceManager.GetString("State80_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменён (80/{0}/{1}).
        /// </summary>
        internal static string State80_X {
            get {
                return ResourceManager.GetString("State80_X", resourceCulture);
            }
        }
    }
}
