//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18052
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;request type=&quot;check&quot;&gt;
        ///	&lt;provider name=&quot;rt&quot; /&gt;
        ///	&lt;phone&gt;{0}&lt;/phone&gt;
        ///&lt;/request&gt;.
        /// </summary>
        internal static string req_RT_CHECK1 {
            get {
                return ResourceManager.GetString("req_RT_CHECK1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;request type=&quot;check&quot;&gt;
        ///	&lt;provider name=&quot;rt&quot; /&gt;
        ///	&lt;!-- svcTypeId --&gt;
        ///	&lt;service&gt;{0}&lt;/service&gt;
        ///	&lt;account&gt;{1}&lt;/account&gt;
        ///	&lt;!-- svcSubNum --&gt;
        ///	&lt;number&gt;{2}&lt;/number&gt;
        ///	&lt;amount&gt;{3}&lt;/amount&gt;
        ///&lt;/request&gt;.
        /// </summary>
        internal static string req_RT_CHECK2 {
            get {
                return ResourceManager.GetString("req_RT_CHECK2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;request type=&quot;check&quot;&gt;
        ///	&lt;provider name=&quot;rt&quot; /&gt;
        ///	&lt;phone&gt;{0}&lt;/phone&gt;
        ///	&lt;!-- Субсчет --&gt;
        ///	&lt;number&gt;{1}&lt;/number&gt;
        ///	&lt;amount&gt;{2}&lt;/amount&gt;
        ///&lt;/request&gt;.
        /// </summary>
        internal static string req_RT_CHECK3 {
            get {
                return ResourceManager.GetString("req_RT_CHECK3", resourceCulture);
            }
        }
    }
}
