//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.19448
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oldi.Ekt.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oldi.Ekt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверно указан номер.
        /// </summary>
        internal static string Code1 {
            get {
                return ResourceManager.GetString("Code1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фатальная ошибка провайдера.
        /// </summary>
        internal static string Code10 {
            get {
                return ResourceManager.GetString("Code10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нехватка средств (без повторов).
        /// </summary>
        internal static string Code12 {
            get {
                return ResourceManager.GetString("Code12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутренняя: Таймаут обработки.
        /// </summary>
        internal static string Code13 {
            get {
                return ResourceManager.GetString("Code13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутренняя: Платеж отменен плательщиком.
        /// </summary>
        internal static string Code14 {
            get {
                return ResourceManager.GetString("Code14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутренняя: Нехватка средств на счете агента.
        /// </summary>
        internal static string Code15 {
            get {
                return ResourceManager.GetString("Code15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутренняя: Отменена тех.поддержкой.
        /// </summary>
        internal static string Code16 {
            get {
                return ResourceManager.GetString("Code16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат идентификатора абонента (КабINET).
        /// </summary>
        internal static string Code17 {
            get {
                return ResourceManager.GetString("Code17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет связи с сервером провайдера (24).
        /// </summary>
        internal static string Code18 {
            get {
                return ResourceManager.GetString("Code18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыт шлюз у оператора.
        /// </summary>
        internal static string Code19 {
            get {
                return ResourceManager.GetString("Code19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверно указан номер.
        /// </summary>
        internal static string Code2 {
            get {
                return ResourceManager.GetString("Code2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прием платежа блокирован на стороне провайдера.
        /// </summary>
        internal static string Code20 {
            get {
                return ResourceManager.GetString("Code20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка Базы Данных у провайдера.
        /// </summary>
        internal static string Code21 {
            get {
                return ResourceManager.GetString("Code21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный номер телефона/счета(Евротел).
        /// </summary>
        internal static string Code22 {
            get {
                return ResourceManager.GetString("Code22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма вне допустимого диапазона.
        /// </summary>
        internal static string Code3 {
            get {
                return ResourceManager.GetString("Code3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно средств на счете провайдера.
        /// </summary>
        internal static string Code30 {
            get {
                return ResourceManager.GetString("Code30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервис не подключен.
        /// </summary>
        internal static string Code33 {
            get {
                return ResourceManager.GetString("Code33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер провайдера недоступен.
        /// </summary>
        internal static string Code4 {
            get {
                return ResourceManager.GetString("Code4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка авторизации.
        /// </summary>
        internal static string Code5 {
            get {
                return ResourceManager.GetString("Code5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер оператора недоступен.
        /// </summary>
        internal static string Code6 {
            get {
                return ResourceManager.GetString("Code6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общая ошибка провайдера.
        /// </summary>
        internal static string Code7 {
            get {
                return ResourceManager.GetString("Code7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фатальная ошибка платежной системы.
        /// </summary>
        internal static string Code8 {
            get {
                return ResourceManager.GetString("Code8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверные параметры проведения.
        /// </summary>
        internal static string Code9 {
            get {
                return ResourceManager.GetString("Code9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка вставки операции в БД.
        /// </summary>
        internal static string State_1 {
            get {
                return ResourceManager.GetString("State_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платеж не найден при проверке статуса.
        /// </summary>
        internal static string State_2 {
            get {
                return ResourceManager.GetString("State_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый.
        /// </summary>
        internal static string State0 {
            get {
                return ResourceManager.GetString("State0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Финансовый контроль.
        /// </summary>
        internal static string State10 {
            get {
                return ResourceManager.GetString("State10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готов к списанию.
        /// </summary>
        internal static string State201 {
            get {
                return ResourceManager.GetString("State201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Списание средств со счета.
        /// </summary>
        internal static string State202_3 {
            get {
                return ResourceManager.GetString("State202_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно средств на счете.
        /// </summary>
        internal static string State204 {
            get {
                return ResourceManager.GetString("State204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Списание.
        /// </summary>
        internal static string State20x {
            get {
                return ResourceManager.GetString("State20x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готов к проведению.
        /// </summary>
        internal static string State401 {
            get {
                return ResourceManager.GetString("State401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проведение.
        /// </summary>
        internal static string State402_3 {
            get {
                return ResourceManager.GetString("State402_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка проведения.
        /// </summary>
        internal static string State404_5 {
            get {
                return ResourceManager.GetString("State404_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проведение.
        /// </summary>
        internal static string State40x {
            get {
                return ResourceManager.GetString("State40x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платёж проведён.
        /// </summary>
        internal static string State60 {
            get {
                return ResourceManager.GetString("State60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка проведения.
        /// </summary>
        internal static string State80 {
            get {
                return ResourceManager.GetString("State80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно средств на счете.
        /// </summary>
        internal static string State80_4 {
            get {
                return ResourceManager.GetString("State80_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка проведения.
        /// </summary>
        internal static string State80_5 {
            get {
                return ResourceManager.GetString("State80_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другая ошибка.
        /// </summary>
        internal static string State80_6 {
            get {
                return ResourceManager.GetString("State80_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платеж отменен вручную.
        /// </summary>
        internal static string State801_2_3 {
            get {
                return ResourceManager.GetString("State801_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;request point=&quot;{0}&quot;&gt;
        ///	&lt;payment service=&quot;{1}&quot; sum=&quot;{2}&quot; sum-in=&quot;{3}&quot; id=&quot;{4}&quot; check=&quot;{5}&quot; date=&quot;{6}&quot;&gt;
        ///		&lt;attribute name=&quot;{7}&quot; value=&quot;{8}&quot; /&gt;
        ///	&lt;/payment&gt;
        ///&lt;/request&gt;.
        /// </summary>
        internal static string Template_Id1 {
            get {
                return ResourceManager.GetString("Template_Id1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;request point=&quot;{0}&quot;&gt;&lt;payment account=&quot;{1}&quot; service=&quot;{2}&quot; sum=&quot;{3}&quot; id=&quot;{4}&quot; check=&quot;{5}&quot; date=&quot;{6}&quot;&gt;{7}&lt;/payment&gt;&lt;/request&gt;.
        /// </summary>
        internal static string Template_Payment {
            get {
                return ResourceManager.GetString("Template_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;request point=&quot;{0}&quot;&gt;
        ///	&lt;payment account=&quot;{1}&quot; service=&quot;{2}&quot; sum=&quot;{3}&quot; sum-in=&quot;{4}&quot; id=&quot;{5}&quot; check=&quot;{6}&quot; date=&quot;{7}&quot;&gt;
        ///		&lt;attribute name=&quot;id2&quot; value=&quot;{8}&quot; /&gt;
        ///	&lt;/payment&gt;
        ///&lt;/request&gt;.
        /// </summary>
        internal static string Template_Payment_1668 {
            get {
                return ResourceManager.GetString("Template_Payment_1668", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;request point=&quot;{0}&quot;&gt;&lt;payment account=&quot;{1}&quot; service=&quot;{2}&quot; sum=&quot;{3}&quot; sum-in=&quot;{4}&quot; id=&quot;{5}&quot; check=&quot;{6}&quot; date=&quot;{7}&quot;&gt;&lt;attribute name=&quot;id2&quot; value=&quot;{8}&quot; /&gt;&lt;attribute name=&quot;fio&quot; value=&quot;{9}&quot; /&gt;&lt;attribute name=&quot;address&quot; value=&quot;{10}&quot; /&gt;&lt;attribute name=&quot;ee&quot; value=&quot;{11}&quot; /&gt;&lt;/request&gt;.
        /// </summary>
        internal static string Template_Payment_605 {
            get {
                return ResourceManager.GetString("Template_Payment_605", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;request point=&quot;{0}&quot;&gt;&lt;status id=&quot;{1}&quot; /&gt;&lt;/request&gt;.
        /// </summary>
        internal static string Template_Status {
            get {
                return ResourceManager.GetString("Template_Status", resourceCulture);
            }
        }
    }
}
