//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.36213
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oldi.Ekt.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oldi.Ekt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;request point=&quot;{0}&quot;&gt;
        ///	&lt;payment account=&quot;{1}&quot; service=&quot;{2}&quot; sum=&quot;{3}&quot; sum-in=&quot;{4}&quot; id=&quot;{5}&quot; check=&quot;{6}&quot; date=&quot;{7}&quot; /&gt;
        ///&lt;/request&gt;.
        /// </summary>
        internal static string Template_Id1 {
            get {
                return ResourceManager.GetString("Template_Id1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;request point=&quot;{0}&quot;&gt;
        ///	&lt;payment service=&quot;{1}&quot; sum=&quot;{2}&quot; sum-in=&quot;{3}&quot; id=&quot;{4}&quot; check=&quot;{5}&quot; date=&quot;{6}&quot;&gt;
        ///		&lt;attribute name=&quot;id2&quot; value=&quot;{7}&quot; /&gt;
        ///	&lt;/payment&gt;
        ///&lt;/request&gt;.
        /// </summary>
        internal static string Template_Id2 {
            get {
                return ResourceManager.GetString("Template_Id2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;request point=&quot;{0}&quot;&gt;&lt;payment account=&quot;{1}&quot; service=&quot;{2}&quot; sum=&quot;{3}&quot; sum-in=&quot;{4}&quot; id=&quot;{5}&quot; check=&quot;{6}&quot; date=&quot;{7}&quot;&gt;{8}&lt;/payment&gt;&lt;/request&gt;.
        /// </summary>
        internal static string Template_Payment {
            get {
                return ResourceManager.GetString("Template_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;request point=&quot;{0}&quot;&gt;
        ///	&lt;payment account=&quot;{1}&quot; service=&quot;{2}&quot; sum=&quot;{3}&quot; sum-in=&quot;{4}&quot; id=&quot;{5}&quot; check=&quot;{6}&quot; date=&quot;{7}&quot;&gt;
        ///		&lt;attribute name=&quot;id2&quot; value=&quot;{8}&quot; /&gt;
        ///	&lt;/payment&gt;
        ///&lt;/request&gt;.
        /// </summary>
        internal static string Template_Payment_1668 {
            get {
                return ResourceManager.GetString("Template_Payment_1668", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;request point=&quot;{0}&quot;&gt;&lt;payment account=&quot;{1}&quot; service=&quot;{2}&quot; sum=&quot;{3}&quot; sum-in=&quot;{4}&quot; id=&quot;{5}&quot; check=&quot;{6}&quot; date=&quot;{7}&quot;&gt;&lt;attribute name=&quot;id2&quot; value=&quot;{8}&quot; /&gt;&lt;attribute name=&quot;fio&quot; value=&quot;{9}&quot; /&gt;&lt;attribute name=&quot;address&quot; value=&quot;{10}&quot; /&gt;&lt;attribute name=&quot;ee&quot; value=&quot;{11}&quot; /&gt;&lt;/payment&gt;&lt;/request&gt;.
        /// </summary>
        internal static string Template_Payment_605 {
            get {
                return ResourceManager.GetString("Template_Payment_605", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;request point=&quot;{0}&quot;&gt;
        ///	&lt;payment service=&quot;{1}&quot; account=&quot;{7}&quot; sum=&quot;{2}&quot; sum-in=&quot;{3}&quot; id=&quot;{4}&quot; check=&quot;{5}&quot; date=&quot;{6}&quot;&gt;
        ///		&lt;attribute name=&quot;id2&quot; value=&quot;{8}&quot; /&gt;
        ///	&lt;/payment&gt;
        ///&lt;/request&gt;.
        /// </summary>
        internal static string Template_Payment_Id1Id2 {
            get {
                return ResourceManager.GetString("Template_Payment_Id1Id2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;request point=&quot;{0}&quot;&gt;
        ///	&lt;payment service=&quot;{1}&quot; account=&quot;{7}&quot; sum=&quot;{2}&quot; sum-in=&quot;{3}&quot; id=&quot;{4}&quot; check=&quot;{5}&quot; date=&quot;{6}&quot;&gt;
        ///		&lt;attribute name=&quot;phone&quot; value=&quot;{8}&quot; /&gt;
        ///	&lt;/payment&gt;
        ///&lt;/request&gt;.
        /// </summary>
        internal static string Template_Payment_Id1Phone {
            get {
                return ResourceManager.GetString("Template_Payment_Id1Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;request point=&quot;{0}&quot;&gt;&lt;status id=&quot;{1}&quot; /&gt;&lt;/request&gt;.
        /// </summary>
        internal static string Template_Status {
            get {
                return ResourceManager.GetString("Template_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;.
        /// </summary>
        internal static string Template_XmlHeader {
            get {
                return ResourceManager.GetString("Template_XmlHeader", resourceCulture);
            }
        }
    }
}
